app/models.py
from app import create_app, db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager 


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password = db.Column(db.String(255))
    password_hash = db.Column(db.String(255))


    @property
    def password(self):
        raise AttributeError('You cannnot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)



    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)

    def __repr__(self):
        return f'User {self.username}'

class Pitch(db.Model):
    __tablename__ = 'pitches'
    id = db.Column('pitch_id', db.Integer, primary_key=True)
    title = db.Column(db.String(60))
    text = db.Column(db.String(300))
    def __init__(self, title, text):
        self.title = title
        self.text = text

    

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,ValidationError
from wtforms.validators import Required,Email
from ..models import User

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
        



    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/auth')
 
    # configure UploadSet
    configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from flask_login import login_required
from . import main
from ..models import User
from .forms import UpdateProfile
from ..models import User, Pitch
from .. import db,photos


@main.route('/')
def index():
    return render_template('index.html',
        pitches=Pitch.query.all()
    )

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/new', methods=['GET', 'POST'])
@login_required
def new():
    if request.method == 'POST':
        new_pitch = Pitch(request.form['title'], request.form['text'])
        db.session.add(new_pitch)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('new-pitch.html') 

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))   
      

app/templates/base.html
{% extends 'bootstrap/base.html' %}

<!-- Navbar block  -->
{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

<!-- Content block -->

{% block content %}

{% endblock%}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
<h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}
{% block content %}

<div class="jumbotron container center">
    <h1>Pitch Project</h1>
    <p>You have a minute to pitch your brilliant ideas for users to give feedback</p>
    <a href="{{ url_for('main.new') }}"><button class="btn btn-success">Pitch </button></a>
</div>
{%- for pitch in pitches %}
<div class="jumbotron container">
    <h3><a href="/posts/{{ pitch.id }}">{{ pitch.title }}</a></h3>
    <p>{{ pitch.text }}</p>
</div>
{%- endfor %}
{% endblock %}

app/templates/navbar.html
<div id="navigator" class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> Pitche's </a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
            <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
            {% else %}
            <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
            {%endif%}
        </ul>
    </div>
</div>

app/templates/new-pitch.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <form action="" method=post class="form-horizontal">
        <h2>Create New Pitch</h2>
        <div class="control-group">
            <div class="controls">
                <input type="text" id="title" name="title" class="input-xlarge form-control" placeholder="Title"
                    value="{{ request.form.title }}" required>
            </div>
        </div>

        <div class="control-group">
            <div class="controls">
                <textarea name="text" rows=10 class="input-xlarge  form-control" placeholder="Post pitch Here"
                    required>{{ request.form.text }}</textarea>
            </div>
        </div>

        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn btn-success">Pitch</button>
                <a href="{{ url_for('main.index') }}">Back to Pitches</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
        <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>

            <!--Displaying user bio-->
            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}
        </div>
        <!--Display profile photo-->
        <div class="col-md-4">
            {% if user.profile_pic_path %}
        
            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
        
            {%else%}
            <p>No profile picture</p>
        
            {% endif %}
        
            {% if user == current_user %}
            <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">
        
                <input type="file" name="photo" class="form-control" required>
                <input type="submit">
            </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    {{wtf.quick_form(form)}}
</div>
{% endblock %}